### ISSUE TITLE
Delete row problem (1.3.1)

### ISSUE THREAD

**Issue by FragmentedRose** [sbuberl/fSQL#23] opened 2019-05-31 21:55 UTC
I do hope I am posting to the right place. The link from Flat-file SQL on sourceforge brought me here. 
Also this is about version 1.3.1 and I see mention on this site to a 1.4... I have no idea if or how to make the 1.4 on this site, work...   Anyway... 

Lets see if I can explain this...  If I create a database with three columns ID, fruit, and amount, and I populate it with entries the text get in my database is shown below... 

10
0: 1;'Strawberry';22;
1: 2;'Apple';22;
2: 3;'Peach';22;
3: 4;'Plum';42;
4: 5;'Mango';42;
5: 6;'Cherry';22;
6: 7;'Orange';68;
7: 8;'Lemon';62;
8: 9;'Lime';50;
9: 10;'Banana';18;

The database works just fine. 

Now lets say I use the delete command to remove Plum, Mango, Orange and Lemon. I am left with what is below and this is where the problem starts. 

6
0: 1;'Strawberry';22;
1: 2;'Apple';22;
2: 3;'Peach';22;
5: 6;'Cherry';22;
8: 9;'Lime';50;
9: 10;'Banana';18;

There is two problems that can happen at this point... Well one that can happen and the second that never seems to fail to happen. 

Problem 1, the one that always happens)  Lets say I get a shipment of Pineapples, Oranges and Watermelons, 100 of each. I want to add them to the database, so I do.  

The database ends up looking as follows: 

7
0: 1;'Strawberry';22;
1: 2;'Apple';22;
2: 3;'Peach';22;
5: 6;'Cherry';22;
8: 9;'Lime';50;
9: 10;'Banana';18;
10: 7;'Pineapple';100;

Notice the Oranges and Watermelons are not added.

Now, nothing I do will allow me to add any more entries. This seems like a bug. Now I have tried repeating this, without my ID column so the database looks like: 

10
0: 'Strawberry';22;
1: 'Apple';22;
2: 'Peach';22;
3: 'Plum';42;
4: 'Mango';42;
5: 'Cherry';22;
6: 'Orange';68;
7: 'Lemon';62;
8: 'Lime';50;
9: 'Banana';18;

But the problem still happens.   

The only way I have found to solve the issue is to manually change the leading numbers... So, 

6
0: 1;'Strawberry';22;
1: 2;'Apple';22;
2: 3;'Peach';22;
5: 6;'Cherry';22;
8: 9;'Lime';50;
9: 10;'Banana';18;

Becomes...

6
0: 1;'Strawberry';22;
1: 2;'Apple';22;
2: 3;'Peach';22;
3: 6;'Cherry';22;
4: 9;'Lime';50;
5: 10;'Banana';18; 

When that is done the database works normally again, but it is not really feasible to manually edit the database each time a row is deleted when the database can have hundreds or more entries... Would you have any idea on how to fix this problem, or is it a intended design? 

Oh and the second issue that shows up sometimes is that once a row has been deleted, any row after the one that was removed may or may not be able to be read and may or may not be able to be altered or updated. 

Thank you for any assistance you might be able to provide.

**Comment by sbuberl** [comment] 2019-06-01 14:14
1.4 isn't officially out yet.  The master branch of this repo is what is 1.4 will be released from after I close a few more issues.

1.3.1 is very old and very buggy and has no unit tests.  Can you try again with the latest from here?Download or clone this repo and check out the [Master Branch Tutorial](http://www.sbuberl.com/fSQL/tutorial_master.html)

And the table entries keys not resetting is intended design (still in use in the master).  So it if callers are referencing say row 2, it's the same row 2 in both cases.   And if it a row is added, it's given the next available.  I at one point played with setting unique ids for the table entry keys, but hasn't made into the master branch yet.  Not sure why resetting them would fix anything.

If you're still having issues, let me know and I will look into them.

**Comment by FragmentedRose** [comment] 2019-06-02 07:03
Forgive me if I seem stupid with this, but you say to try the new new version... From the Master Branch.  Your link mentions:  require_once("Environment.php");    So I assume I need that file, which can be found  here https://github.com/sbuberl/fSQL/tree/master/src  (I can't find it anywhere else...)   But when I try to run it I get a message that reads:  You must set up the project dependencies, run the following commands: curl -sS https://getcomposer.org/installer | php php composer.phar install

Does that mean I have to compile Environment.php before I can use it, because to be honest I have no clue how to do that.

**Comment by jasteele12** [comment] 2019-06-02 08:09
Most modern-day PHP packages and frameworks use composer, a PHP dependency manager.

To learn more (it really only takes a few minutes to understand and use) start here: [https://getcomposer.org/doc/00-intro.md](https://getcomposer.org/doc/00-intro.md)

**Comment by sbuberl** [comment] 2019-06-04 18:54
I'm going to test this after work with the master.

**Comment by sbuberl** [comment] 2019-06-05 01:41
Added test for this bug using master that passes so I'm going to close this.  

https://github.com/sbuberl/fSQL/blob/master/tests/RegressionTest.php

Let me know if you have any more questions.

**Closed by sbuberl** 2019-06-05 01:41 UTC
Labels: bug
